// auto generated by go tool dist
// goos=windows goarch=amd64

#include "runtime.h"
void
runtime·GOMAXPROCS(intgo n, intgo ret)
{
#line 8 "C:\Users\ADMINI~1\AppData\Local\Temp\2\bindist417694871\go\src\pkg\runtime\runtime1.goc"

	ret = runtime·gomaxprocsfunc(n);
	FLUSH(&ret);
}
void
runtime·NumCPU(intgo ret)
{
#line 12 "C:\Users\ADMINI~1\AppData\Local\Temp\2\bindist417694871\go\src\pkg\runtime\runtime1.goc"

	ret = runtime·ncpu;
	FLUSH(&ret);
}
